namespace: prod
image:
  repository: us-central1-docker.pkg.dev/gcp-iot-core-361019/ae-omnicore-dev-infra/nginx
  tag: latest
  pullPolicy: IfNotPresent
configMapData:
  html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>prod</title>
    </head>
    <body>

    <h1>prod</h1>

    </body>
    </html>
