namespace: prod
image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent
configMapData:
  html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>prod</title>
    </head>
    <body>

    <h1>prod</h1>

    </body>
    </html>
